config/routes.rb
Rails.application.routes.draw do
  get "/bienvenida", to: "home#index";

  root to:"home#index"
  get "users/new", to: "users#new" , as: :new_users
  get "users/:id", to: "users#show"
  get "users/:id/edit", to: "users#edit"
  get "users", to: "users#index"
  patch "/users/:id", to: "users#update", as: :user
  post "users", to: "users#create"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :find_article, only: [:edit, :update, :show]

    def new
        @user = User.new
    end
    
    def index
        @users = User.all
    end
    
    def create  
        @user = User.create(user:params[:user][:user],password:params[:user][:password],name:params[:user][:name],
         secondname:params[:user][:secondname],lastname:params[:user][:lastname],sec_lastname:params[:user][:sec_lastname],
         identification:params[:user][:identification],number_identification:params[:user][:number_identification],
         age:params[:user][:age])
         redirect_to @user
     end

    def update
        @user.update(user:params[:user][:user],password:params[:user][:password],name:params[:user][:name],
            secondname:params[:user][:secondname],lastname:params[:user][:lastname],sec_lastname:params[:user][:sec_lastname],
            identification:params[:user][:identification],number_identification:params[:user][:number_identification],
            age:params[:user][:age])
            redirect_to @user
    end
    
    def find_article
        @user = User.find(params[:id]) 
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/index.html.erb
<h1>Bienvenido</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "partials/nav" %>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav style="margin-top:50px">
<ul>
    <li>
        <%= link_to "Inicio", root_path%>
    </li>
      <li>
        <%= link_to "Nuevo Usuario", new_users_path%>
    </li>
     <li>
        <%= link_to "Usuarios", users_path%>
    </li>
</ul>
</nav>

<style>
   *{
       margin:0;
       padding:0;
   }
   nav {
    margin-top: 50px;
    width:100%;
}
nav ul {
    list-style: none;
}
nav > ul {
    display: table;
    overflow: hidden;
    width:100%;
    background:#000000;
    position: relative;
}
nav > ul li {
    display: table-cell;
}
nav > ul > li > ul {
    display: none;
}
nav > ul li a {
    color: #FFFFFF;
    display: block;
    line-height: 20px;
    padding: 20px;
    position: relative;
    text-align: center;
    text-decoration: none;
}
</style>

app/views/users/_form.html.erb
<%= form_with(model:@user,local:true) do|form|%>
    <div id="from">
         <%=form.label :user %>
         <%=form.text_field :user %>
         <%=form.label :password %>
         <%=form.text_field :password %>
         <%=form.label :name %>
         <%=form.text_field :name %>
         <%=form.label :secondname %>
         <%=form.text_field :secondname %>
         <%=form.label :lastname %>
         <%=form.text_field :lastname %>
         <%=form.label :sec_lastname %>
         <%=form.text_field :sec_lastname %>
         <%=form.label :identification %>
         <%=form.text_field :identification %>
         <%=form.label :number_identification %>
         <%=form.text_field :number_identification %>
         <%=form.label :age %>
         <%=form.text_field :age %>

    <div id="boton">
        <%=form.submit%>
    </div>

    </div>
    <style>
    form {
        position: relative;
        width  : 740px;
        height : 498px;
        margin : 0 auto;
    }
    label {
        font : .8em "typewriter", sans-serif;
    }
    #from {
        position: absolute;
        left : 300px;
        top  : 35px;
    }
    input {
    height: 2.5em;
    vertical-align: middle; 
    display:block;
    }
    #boton {
        left         : 440px;
        top          : 360px;
        padding      : 5px;
        font         : bold .6em sans-serif;
        border       : 2px solid #333;
        border-radius: 5px;
        background   : none;
        cursor       : pointer;
    }
    #boton:hover,
    #boton:focus {
        outline   : none;
        background: #000;
        color   : #FFF;
    }
</style>
<%end%>

app/views/users/_user.html.erb
<table summary="Usuarios">
  <caption>Usuarios</caption>
  <thead>
    <tr>
      <th scope="col">Usuario</th>
      <th scope="col">Contraseña</th>
      <th scope="col">Nombre</th>
      <th scope="col">Apellido</th>
      <th scope="col">Ver Más</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%=user.user%></th>
      <td><%=user.password%></td>
      <td><%=user.name%></td>
      <td><%=user.lastname%></td>
      <td><%= link_to "Ver más",user %></td>
    </tr>
</table>

<style>
table {
   width: 70%;
   border: 1px solid #000;
}
caption {
   padding: 0.3em;
   color: #fff;
    background: #000;
}
th, td {
   width: 25%;
   text-align: center;
   vertical-align: top;
   border: 1px solid #000;
}
</style>

app/views/users/edit.html.erb
<%= render "users/form"%>

app/views/users/index.html.erb
<h1>Mis usuarios</h1>

<%= render @users %>

app/views/users/new.html.erb
<%= render "users/form"%>

app/views/users/show.html.erb
<h1><%=@user.user%></h1>
<h1><%=@user.password%></h1>
<h1><%=@user.name%></h1>
<h1><%=@user.secondname%></h1>
<h1><%=@user.lastname%></h1>
<h1><%=@user.sec_lastname%></h1>
<h1><%=@user.identification%></h1>
<h1><%=@user.number_identification%></h1>
<h1><%=@user.age%></h1>